### ISSUE TITLE
image_grabber.py -> AttributeError: 'module' object has no attribute 'ImageClient'

### ISSUE THREAD

**Issue by MYSystemLogistics** [ifm/o3d3xx-python#14]
I followed all the instructions indicated on the o3d3xx-python page, but when I try to execute the image_grabber.py code I get this error:

![ImageGrabberIssue](https://user-images.githubusercontent.com/58782597/75057779-0b745b00-54da-11ea-9e26-a2738edeb001.png)
```
Traceback (most recent call last):
  File "image_grabber.py", line 12, in <module>
    pcic = o3d3xx.ImageClient(address, 50010)
AttributeError: 'module' object has no attribute 'ImageClient'
```

I'm using an ifm O3D303 ToF camera, I can ping the device and I can see the point-cloud with the ifm3d-pcl-viewer.
I made no modification to the python code.
How can I solve it?

Thanks.

**Comment by theseankelly** [comment]
Have you installed the python module via the instructions in the README?

```
python setup.py install
```

**Comment by MYSystemLogistics** [comment]
Yes, I did.

**Comment by theseankelly** [comment]
Cool, just had to ask the basic question.

@graugans can you have a look or route to the appropriate owner of this package?

**Comment by cfreundl** [comment]
Can you try to execute the example script with
```
python -v image_grabber.py
```
and provide the output here?

**Comment by MYSystemLogistics** [comment]
Here it is:

```
mariglenymeraj@Arcanite:~/ifm/o3d3xx-python/examples$ python -v image_grabber.py
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
# zipimport: found 9 names in /usr/local/lib/python2.7/dist-packages/pointnet2-0.0.0-py2.7-linux-x86_64.egg
# zipimport: found 9 names in /usr/local/lib/python2.7/dist-packages/iou3d-0.0.0-py2.7-linux-x86_64.egg
# zipimport: found 9 names in /usr/local/lib/python2.7/dist-packages/roipool3d-0.0.0-py2.7-linux-x86_64.egg
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
# /usr/lib/python2.7/__future__.pyc matches /usr/lib/python2.7/__future__.py
import __future__ # precompiled from /usr/lib/python2.7/__future__.pyc
import builtins # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/builtins
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/builtins/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/builtins/__init__.py
import builtins # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/builtins/__init__.pyc
import future # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/__init__.py
import future # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/__init__.pyc
import future.builtins # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/__init__.py
import future.builtins # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/__init__.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/iterators.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/iterators.py
import future.builtins.iterators # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/iterators.pyc
import itertools # builtin
import future.utils # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/utils
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/utils/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/utils/__init__.py
import future.utils # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/utils/__init__.pyc
# /usr/lib/python2.7/numbers.pyc matches /usr/lib/python2.7/numbers.py
import numbers # precompiled from /usr/lib/python2.7/numbers.pyc
# /usr/lib/python2.7/functools.pyc matches /usr/lib/python2.7/functools.py
import functools # precompiled from /usr/lib/python2.7/functools.pyc
import _functools # builtin
# /usr/lib/python2.7/copy.pyc matches /usr/lib/python2.7/copy.py
import copy # precompiled from /usr/lib/python2.7/copy.pyc
# /usr/lib/python2.7/weakref.pyc matches /usr/lib/python2.7/weakref.py
import weakref # precompiled from /usr/lib/python2.7/weakref.pyc
# /usr/lib/python2.7/inspect.pyc matches /usr/lib/python2.7/inspect.py
import inspect # precompiled from /usr/lib/python2.7/inspect.pyc
# /usr/lib/python2.7/string.pyc matches /usr/lib/python2.7/string.py
import string # precompiled from /usr/lib/python2.7/string.pyc
import strop # builtin
# /usr/lib/python2.7/dis.pyc matches /usr/lib/python2.7/dis.py
import dis # precompiled from /usr/lib/python2.7/dis.pyc
# /usr/lib/python2.7/opcode.pyc matches /usr/lib/python2.7/opcode.py
import opcode # precompiled from /usr/lib/python2.7/opcode.pyc
import imp # builtin
# /usr/lib/python2.7/tokenize.pyc matches /usr/lib/python2.7/tokenize.py
import tokenize # precompiled from /usr/lib/python2.7/tokenize.pyc
# /usr/lib/python2.7/token.pyc matches /usr/lib/python2.7/token.py
import token # precompiled from /usr/lib/python2.7/token.pyc
import operator # builtin
# /usr/lib/python2.7/collections.pyc matches /usr/lib/python2.7/collections.py
import collections # precompiled from /usr/lib/python2.7/collections.pyc
import _collections # builtin
# /usr/lib/python2.7/keyword.pyc matches /usr/lib/python2.7/keyword.py
import keyword # precompiled from /usr/lib/python2.7/keyword.pyc
# /usr/lib/python2.7/heapq.pyc matches /usr/lib/python2.7/heapq.py
import heapq # precompiled from /usr/lib/python2.7/heapq.pyc
import _heapq # builtin
import thread # builtin
import future.types # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/__init__.py
import future.types # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/__init__.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newbytes.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newbytes.py
import future.types.newbytes # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newbytes.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newobject.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newobject.py
import future.types.newobject # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newobject.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newdict.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newdict.py
import future.types.newdict # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newdict.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newint.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newint.py
import future.types.newint # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newint.pyc
# /usr/lib/python2.7/struct.pyc matches /usr/lib/python2.7/struct.py
import struct # precompiled from /usr/lib/python2.7/struct.pyc
import _struct # builtin
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newlist.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newlist.py
import future.types.newlist # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newlist.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newrange.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newrange.py
import future.types.newrange # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newrange.pyc
import future.backports # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/__init__.py
import future.backports # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/__init__.pyc
import future.standard_library # directory /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/standard_library
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/standard_library/__init__.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/standard_library/__init__.py
import future.standard_library # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/standard_library/__init__.pyc
import logging # directory /usr/lib/python2.7/logging
# /usr/lib/python2.7/logging/__init__.pyc matches /usr/lib/python2.7/logging/__init__.py
import logging # precompiled from /usr/lib/python2.7/logging/__init__.pyc
import time # builtin
import cStringIO # builtin
# /usr/lib/python2.7/threading.pyc matches /usr/lib/python2.7/threading.py
import threading # precompiled from /usr/lib/python2.7/threading.pyc
# /usr/lib/python2.7/atexit.pyc matches /usr/lib/python2.7/atexit.py
import atexit # precompiled from /usr/lib/python2.7/atexit.pyc
# /usr/lib/python2.7/contextlib.pyc matches /usr/lib/python2.7/contextlib.py
import contextlib # precompiled from /usr/lib/python2.7/contextlib.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/misc.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/misc.py
import future.backports.misc # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/backports/misc.pyc
# /usr/lib/python2.7/subprocess.pyc matches /usr/lib/python2.7/subprocess.py
import subprocess # precompiled from /usr/lib/python2.7/subprocess.pyc
import gc # builtin
import select # builtin
import fcntl # builtin
# /usr/lib/python2.7/pickle.pyc matches /usr/lib/python2.7/pickle.py
import pickle # precompiled from /usr/lib/python2.7/pickle.pyc
import marshal # builtin
import binascii # builtin
import math # builtin
# /usr/lib/python2.7/socket.pyc matches /usr/lib/python2.7/socket.py
import socket # precompiled from /usr/lib/python2.7/socket.pyc
import _socket # builtin
dlopen("/usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so", 2);
import _ssl # dynamically loaded from /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newstr.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newstr.py
import future.types.newstr # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/types/newstr.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/misc.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/misc.py
import future.builtins.misc # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/misc.pyc
# /usr/lib/python2.7/io.pyc matches /usr/lib/python2.7/io.py
import io # precompiled from /usr/lib/python2.7/io.pyc
import _io # builtin
dlopen("/usr/lib/python2.7/lib-dynload/future_builtins.x86_64-linux-gnu.so", 2);
import future_builtins # dynamically loaded from /usr/lib/python2.7/lib-dynload/future_builtins.x86_64-linux-gnu.so
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newnext.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newnext.py
import future.builtins.newnext # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newnext.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newround.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newround.py
import future.builtins.newround # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newround.pyc
# /usr/lib/python2.7/decimal.pyc matches /usr/lib/python2.7/decimal.py
import decimal # precompiled from /usr/lib/python2.7/decimal.pyc
# /usr/lib/python2.7/locale.pyc matches /usr/lib/python2.7/locale.py
import locale # precompiled from /usr/lib/python2.7/locale.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newsuper.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newsuper.py
import future.builtins.newsuper # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/newsuper.pyc
# /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/new_min_max.pyc matches /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/new_min_max.py
import future.builtins.new_min_max # precompiled from /home/mariglenymeraj/.local/lib/python2.7/site-packages/future/builtins/new_min_max.pyc
import o3d3xx # directory /home/mariglenymeraj/ros/o3d3xx/lib/python2.7/dist-packages/o3d3xx
# /home/mariglenymeraj/ros/o3d3xx/lib/python2.7/dist-packages/o3d3xx/__init__.pyc matches /home/mariglenymeraj/ros/o3d3xx/lib/python2.7/dist-packages/o3d3xx/__init__.py
import o3d3xx # precompiled from /home/mariglenymeraj/ros/o3d3xx/lib/python2.7/dist-packages/o3d3xx/__init__.pyc
Traceback (most recent call last):
  File "image_grabber.py", line 12, in <module>
    pcic = o3d3xx.ImageClient(address, 50010)
AttributeError: 'module' object has no attribute 'ImageClient'
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] sysconfig
# cleanup[1] builtins
# cleanup[1] zipimport
# cleanup[1] future.types.newobject
# cleanup[1] token
# cleanup[1] o3d3xx
# cleanup[1] decimal
# cleanup[1] google
# cleanup[1] locale
# cleanup[1] encodings
# cleanup[1] posix
# cleanup[1] math
# cleanup[1] mpl_toolkits
# cleanup[1] _sysconfigdata_nd
# cleanup[1] _functools
# cleanup[1] socket
# cleanup[1] opcode
# cleanup[1] future.types.newrange
# cleanup[1] future.types.newbytes
# cleanup[1] __future__
# cleanup[1] _collections
# cleanup[1] future.types.newdict
# cleanup[1] operator
# cleanup[1] _heapq
# cleanup[1] _socket
# cleanup[1] sre_constants
# cleanup[1] _warnings
# cleanup[1] _codecs
# cleanup[1] sitecustomize
# cleanup[1] _sysconfigdata
# cleanup[1] _struct
# cleanup[1] keyword
# cleanup[1] future
# cleanup[1] google.cloud
# cleanup[1] encodings.aliases
# cleanup[1] exceptions
# cleanup[1] future.types.newint
# cleanup[1] site
# cleanup[1] io
# cleanup[1] strop
# cleanup[1] google.logging
# cleanup[1] zope
# cleanup[1] _ssl
# cleanup[1] future.types.newlist
# cleanup[1] _weakref
# cleanup[1] _io
# cleanup[1] _weakrefset
# cleanup[1] future.types.newstr
# cleanup[1] future_builtins
# cleanup[1] future.standard_library
# cleanup[1] encodings.utf_8
# cleanup[1] future.backports
# cleanup[1] future.backports.misc
# cleanup[1] abc
# cleanup[1] future.types
# cleanup[1] logging
# cleanup[1] thread
# cleanup[1] future.builtins
# cleanup[1] future.builtins.misc
# cleanup[1] atexit
# cleanup[1] contextlib
# cleanup[1] future.builtins.iterators
# cleanup[1] future.builtins.newsuper
# cleanup[1] future.builtins.newround
# cleanup[1] subprocess
# cleanup[1] gc
# cleanup[1] collections
# cleanup[1] future.builtins.new_min_max
# cleanup[1] signal
# cleanup[1] threading
# cleanup[1] cStringIO
# cleanup[1] fcntl
# cleanup[1] codecs
# cleanup[1] future.builtins.newnext
# cleanup[1] pickle
# cleanup[1] traceback
# cleanup[1] itertools
# cleanup[1] marshal
# cleanup[1] select
# cleanup[1] future.utils
# cleanup[1] binascii
# cleanup[1] copy
# cleanup[1] numbers
# cleanup[1] heapq
# cleanup[1] functools
# cleanup[1] struct
# cleanup[1] inspect
# cleanup[1] weakref
# cleanup[1] tokenize
# cleanup[1] imp
# cleanup[1] string
# cleanup[1] dis
# cleanup[1] re
# cleanup[1] _locale
# cleanup[1] sre_compile
# cleanup[1] _sre
# cleanup[1] sre_parse
# cleanup[2] UserDict
# cleanup[2] os
# cleanup[2] posixpath
# cleanup[2] errno
# cleanup[2] os.path
# cleanup[2] copy_reg
# cleanup[2] linecache
# cleanup[2] _abcoll
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] types
# cleanup[2] time
# cleanup sys
# cleanup __builtin__
# cleanup ints: 185 unfreed ints
# cleanup floats: 3 unfreed floats
```

Thank you.
